MCU = RP2040
BOOTLOADER = rp2040
CONVERT_TO = kb2040
SPLIT_KEYBOARD = yes

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = cirque_pinnacle_i2c

OLED_ENABLE = no
OLED_DRIVER = SSD1306
CONSOLE_ENABLE=yes
DEBUG_ENABLE=yes
AUDIO_ENABLE = no

